# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15jIaKbufsRWgmJ7BWyCQqxSf5PgXN2ps
"""

from google.colab import drive
drive.mount('/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /gdrive/MyDrive/Linux

from statistics import mean
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

def remove_outliers(data, threshold = 2):
  z_scores = np.abs(stats.zscore(data))
  filtered_data = data[(z_scores < threshold)]
  return filtered_data

def calculate_most_probable_mean(data):
    # Remove outliers using the Z-score method
    filtered_data = remove_outliers(data)
    # Calculate the mean of the filtered data
    mean = np.mean(filtered_data)
    return mean

dp_data = []
for i in range(0, 1001, 2):
  file = open(f'./dp_data/{i}.txt', 'r')
  lines = file.readlines()
  data= [int(line[:-1]) for line in lines]
  data = np.array(data)
  mean = calculate_most_probable_mean(data)
  dp_data.append(mean)

fd_data = []
for i in range(0, 1001, 2):
  file = open(f'./fd_data/{i}.txt', 'r')
  lines = file.readlines()
  data= [int(line[:-1]) for line in lines]
  data = np.array(data)
  fd_data.append(calculate_most_probable_mean(data))

index = [i for i in range(0, 1001, 2)]
plt.plot(index, dp_data)
plt.plot(index, fd_data)
plt.show()
